[theme]
base="dark"

primaryColor="#1F6AE1"        # Azul corporativo
backgroundColor="#0E1117"     # Fondo negro azulado
secondaryBackgroundColor="#161B22" 
textColor="#E6EDF3"           # Texto claro suave
font="sans serif"
